spring.datasource.url=jdbc:postgresql://dpg-d75f2jma2pns738shae0-a:5432/portfolio_2ap2
spring.datasource.username=portfolio_user
spring.datasource.password=UPY6pl8hDWGytBdFQ3APIOZEx7xOJk2Z

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.port=8080